name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build and run Docker Compose
      run: |
        docker compose up -d --build

    - name: Wait for container
      run: sleep 15

    - name: Test app
      run: curl -f http://localhost:8080
